POST localhost:8081//api/v1/auth/login
Content-Type: application/json;charset=UTF-8

{
  "mail": "test",
  "password": "test"}



###
POST localhost:8081//api/v1/auth/registration
Content-Type: application/json;charset=UTF-8

{
  "mail": "testReg",
  "password": "test",
  "status":  "ACTIVE",
  "role": "USER"
}



###
POST localhost:8081//api/v1/auth/login
Content-Type: application/json;charset=UTF-8

{
  "mail": "testNone",
  "password": "test"}




###
GET localhost:8081//api/v1/auth/current
Content-Type: application/json;charset=UTF-8
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODUwOTk4MDQsImV4cCI6MTY4NTcwNDY4NH0.PG5s62r0dwcXAJWK2AqCGTC5DM-xi07zF5YpOWiKx0w

{
  }



###
GET localhost:8081//api/v1/auth/validation
Content-Type: application/json;charset=UTF-8
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODUwOTk4MDQsImV4cCI6MTY4NTcwNDY4NH0.PG5s62r0dwcXAJWK2AqCGTC5DM-xi07zF5YpOWiKx0w

